import { StyleSheet } from 'react-native';
import { Colors, FontSize, Radius, Space } from '../../constants/tokens';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  keyboard: {
    flex: 1,
  },
  topBar: {
    height: 54,
    paddingHorizontal: Space.s4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backSlot: {
    width: 38,
  },
  backButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDots: {
    flexDirection: 'row',
    gap: Space.s2,
  },
  progressDot: {
    width: 22,
    height: 3,
    borderRadius: Radius.pill,
    backgroundColor: Colors.ink100,
  },
  progressDotActive: {
    backgroundColor: Colors.ink1000,
  },
  screen: {
    flex: 1,
    paddingHorizontal: Space.s5,
    paddingBottom: Space.s5,
  },
  brandMark: {
    width: 112,
    height: 112,
    borderRadius: 56,
    borderWidth: 1,
    borderColor: Colors.hair,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: Space.s10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  kicker: {
    marginTop: Space.s8,
    textAlign: 'center',
    color: Colors.text3,
    fontSize: FontSize.micro,
    fontWeight: '800',
    letterSpacing: 0,
  },
  title: {
    marginTop: Space.s2,
    textAlign: 'center',
    color: Colors.text,
    fontSize: FontSize.display,
    fontWeight: '900',
    letterSpacing: 0,
  },
  description: {
    marginTop: Space.s3,
    textAlign: 'center',
    color: Colors.text3,
    fontSize: FontSize.body,
    lineHeight: 23,
  },
  previewCard: {
    marginTop: Space.s8,
    padding: Space.s4,
    borderRadius: Radius.r3,
    backgroundColor: Colors.ink1000,
  },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  previewTitle: {
    color: Colors.ink25,
    fontSize: FontSize.body,
    fontWeight: '800',
  },
  previewSub: {
    marginTop: 2,
    color: Colors.ink300,
    fontSize: FontSize.small,
    fontWeight: '600',
  },
  previewLines: {
    marginTop: Space.s4,
    gap: Space.s2,
  },
  previewLine: {
    height: 8,
    borderRadius: Radius.pill,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  kakaoButton: {
    minHeight: 54,
    borderRadius: Radius.r2,
    backgroundColor: '#FEE500',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Space.s2,
    marginTop: 'auto',
  },
  kakaoIcon: {
    color: Colors.ink1000,
    fontSize: FontSize.body,
    fontWeight: '900',
  },
  kakaoButtonText: {
    color: Colors.ink1000,
    fontSize: FontSize.body,
    fontWeight: '800',
  },
  sectionTitle: {
    marginTop: Space.s8,
    color: Colors.text,
    fontSize: FontSize.h1,
    fontWeight: '900',
    lineHeight: 30,
    letterSpacing: 0,
  },
  sectionSub: {
    marginTop: Space.s2,
    color: Colors.text3,
    fontSize: FontSize.body,
    lineHeight: 23,
  },
  allAgreeRow: {
    marginTop: Space.s8,
    minHeight: 56,
    paddingHorizontal: Space.s4,
    borderRadius: Radius.r2,
    borderWidth: 1,
    borderColor: Colors.ink1000,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Space.s3,
  },
  allAgreeText: {
    color: Colors.text,
    fontSize: FontSize.body,
    fontWeight: '800',
  },
  termList: {
    marginTop: Space.s3,
    borderTopWidth: 1,
    borderTopColor: Colors.hair,
  },
  termRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: Colors.hair,
    gap: Space.s3,
  },
  termText: {
    flex: 1,
    color: Colors.text2,
    fontSize: FontSize.small,
    fontWeight: '700',
  },
  checkIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.ink1000,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surface,
  },
  checkIconSubtle: {
    borderColor: Colors.border,
  },
  checkIconChecked: {
    borderColor: Colors.ink1000,
    backgroundColor: Colors.ink1000,
  },
  bottomArea: {
    marginTop: 'auto',
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: Radius.r2,
    backgroundColor: Colors.ink1000,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: Colors.ink25,
    fontSize: FontSize.body,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.4,
  },
  formGroup: {
    marginTop: Space.s6,
  },
  label: {
    color: Colors.text,
    fontSize: FontSize.small,
    fontWeight: '800',
    marginBottom: Space.s2,
  },
  input: {
    height: 54,
    borderRadius: Radius.r2,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    paddingHorizontal: Space.s4,
    color: Colors.text,
    fontSize: FontSize.body,
    fontWeight: '700',
  },
  helper: {
    marginTop: Space.s2,
    color: Colors.text3,
    fontSize: FontSize.micro,
    fontWeight: '600',
  },
  segmented: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: Radius.r2,
    backgroundColor: Colors.ink50,
    gap: 4,
  },
  genderButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: Radius.r1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderButtonSelected: {
    backgroundColor: Colors.ink1000,
  },
  genderText: {
    color: Colors.text3,
    fontSize: FontSize.small,
    fontWeight: '800',
  },
  genderTextSelected: {
    color: Colors.ink25,
  },
  errorBox: {
    marginTop: Space.s5,
    padding: Space.s3,
    borderRadius: Radius.r2,
    backgroundColor: '#FCEEEE',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Space.s2,
  },
  errorText: {
    flex: 1,
    color: '#8C1D18',
    fontSize: FontSize.small,
    lineHeight: 19,
    fontWeight: '700',
  },
});
